### ISSUE TITLE
Search results not clickable

### ISSUE THREAD

**Issue by Mennaruuk** [yuran1811/Music-Player#1]
Hi!! Tôi hy vọng bạn đang làm tốt!

Your app works nicely. Cool design. I did notice, however, that search results are not clickable. For example, you can search for Taylor Swift. The results don't appear at all, that's another problem. But when you click the search bar, you'll see suggestions like _Sweetest Pie_ that are unclickable.

Demo:

https://user-images.githubusercontent.com/52135169/157813705-14d5e604-a9d1-48de-baa4-a502e7d7860e.mp4

Do you know what is happening here? Thank you.

**Comment by yuran1811** [comment]
You can find out in README that it's the feature in the future
